version: '2'

volumes:
  redis-data:
    driver: local

services:
  redis:
    image: hypriot/rpi-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  base:
    build:
      context: .
      restart: always
      dockerfile: Dockerfile.base

  web:
    build:
      context: .
      dockerfile: Dockerfile.web

    ports:
      - '80:3000'
    links:
      - redis
    environment:
      - NODE_ENV=production

  kue:
    build:
      context: .
      dockerfile: Dockerfile.kue
    links:
      - redis
    environment:
      - NODE_ENV=production

  serialport:
    build:
      context: .
      dockerfile: Dockerfile.serialport
    links:
      - redis
    devices:
      - '/dev/ttyUSB0'
    environment:
      - NODE_ENV=production
